(() => {
  const CATEGORIES = {
    'Herd Mentality': [
      'Are you a cat person or a dog person?',
      'Are you a mountain person or a beach person?',
      'How many pillows are too many for a bed?',
      'How many slices of pizza is the normal amount to eat?',
      'If you flipped a coin right now, would you call heads or tails?',
      'If you had to choose only one pizza topping, what would it be?',
      'If you had to describe the color "Blue" to a blind person, what word would you use?',
      'If you had to describe the color "Red" to a blind person, what word would you use?',
      'Is a burger a sandwich?',
      'Is a hot dog a sandwich?',
      'Name a "sport" that shouldn\'t actually be a sport.',
      'Name a bad habit.',
      'Name a beverage you drink hot.',
      'Name a bird that cannot fly.',
      'Name a body part you have two of.',
      'Name a brand of luxury car.',
      'Name a brand of luxury watch.',
      'Name a card game that everyone knows how to play.',
      'Name a cartoon character that is very annoying.',
      'Name a celebrity who seems "down to earth."',
      'Name a celebrity who would be a great President.',
      'Name a chore you always put off until the last minute.',
      'Name a common excuse for being late to work.',
      'Name a common farm animal.',
      'Name a common hobby for retired people.',
      'Name a common office snack.',
      'Name a condiment you cannot live without.',
      'Name a condiment you keep in the fridge.',
      'Name a dream job for a 15-year-old.',
      'Name a dream job for a 5-year-old.',
      'Name a drink that is best served with lots of ice.',
      'Name a European capital city.',
      'Name a famous "Chris"?',
      'Name a famous "John"?',
      'Name a famous "Michael"?',
      'Name a famous "Tom"?',
      'Name a famous wizard.',
      'Name a fashion accessory that is actually quite useless.',
      'Name a flower that smells amazing.',
      'Name a food that is better as a leftover.',
      'Name a food that is impossible to eat gracefully.',
      'Name a fruit that tastes sour.',
      'Name a fruit you have to peel before eating.',
      'Name a good habit.',
      'Name a habit that is hard to break.',
      'Name a hairstyle that was popular but is now cringe.',
      'Name a hobby that makes someone look intellectual.',
      'Name a job that is harder than it looks.',
      'Name a job that requires wearing a uniform.',
      'Name a kitchen appliance you use almost every day.',
      'Name a land animal that can swim.',
      'Name a language everyone should learn.',
      'Name a member of the Beatles.',
      'Name a month with 30 days.',
      'Name a month with 31 days.',
      'Name a movie that everyone has seen at least 2 times.',
      'Name a movie that made you cry.',
      'Name a musical instrument that is hard to play.',
      'Name a musical instrument with strings.',
      'Name a musical instrument you blow into.',
      'Name a mythical creature you wish was real.',
      'Name a personality trait that is contagious.',
      'Name a piece of clothing you should never wear to a wedding.',
      'Name a place with a huge amount of sand.',
      'Name a planet (besides Earth).',
      'Name a plant that is easy to keep alive.',
      'Name a playground game you played as a kid.',
      'Name a prehistoric animal (besides a T-Rex).',
      'Name a primary color.',
      'Name a profession that earns a lot of respect.',
      'Name a reality TV show that is a guilty pleasure.',
      'Name a reason someone might "ghost" a person.',
      'Name a red fruit (skin or flesh).',
      'Name a retro piece of tech you miss.',
      'Name a smell that belongs in a kitchen.',
      'Name a social media app that is "dying."',
      'Name a song that everyone knows the lyrics to.',
      'Name a sound that is universally annoying.',
      'Name a sound that makes you sleepy.',
      'Name a sport played with a racket.',
      'Name a tech brand that people are "loyal" to.',
      'Name a toy that will never go out of style.',
      'Name a tree that is easy to identify.',
      'Name a TV show you can watch over and over.',
      'Name a type of hat that is hard to pull off.',
      'Name a type of nut found in a trail mix.',
      'Name a vegetable children usually hate.',
      'Name a vegetable that is better raw than cooked.',
      'Name a video game character everyone knows.',
      'Name a word that is hard to spell.',
      'Name a word that sounds funny.',
      'Name a word that starts with "Z".',
      'Name a yellow fruit (skin or flesh).',
      'Name an animal that is surprisingly fast.',
      'Name an animal that lives in the ocean.',
      'Name an animal that would be terrifying if it were 1 meter tall.',
      'Name something people lie about on their resumes.',
      'Name something that is sticky.',
      'Name something you always forget to pack for vacation.',
      'Name something you can do in under 60 seconds.',
      'Name your favorite finger.',
      'What do you put in coffee: milk or sugar?',
      'What is a common pizza topping?',
      'What is a popular travel destination that is overrated?',
      'What is the best "Friday feeling" activity?',
      'What is the best age to be?',
      'What is the best age to retire?',
      'What is the best board game of all time?',
      'What is the best camping food?',
      'What is the best color for a car?',
      'What is the best color for a dress?',
      'What is the best color for a highlighter pen?',
      'What is the best color for a pair of shoes?',
      'What is the best comfort movie?',
      'What is the best day to go grocery shopping?',
      'What is the best day to work from home?',
      'What is the best dip for chips?',
      'What is the best fast-food burger chain?',
      'What is the best fast-food fried chicken chain?',
      'What is the best flavor of ice cream?',
      'What is the best flavor of potato chip?',
      'What is the best flower to receive as a gift?',
      'What is the best invention of the last 100 years?',
      'What is the best outdoor activity for a first date?',
      'What is the best prize to win in a competition?',
      'What is the best protein source?',
      'What is the best room to have a TV in?',
      'What is the best scent for a candle?',
      'What is the best season of the year?',
      'What is the best seat on a plane: window or aisle?',
      'What is the best shape for pasta?',
      'What is the best sitcom of all time?',
      'What is the best streaming service?',
      'What is the best superpower?',
      'What is the best theme park in the world?',
      'What is the best thing to put on a piece of toast?',
      'What is the best time to have dinner?',
      'What is the best time to have lunch?',
      'What is the best traditional dish from your country?',
      'What is the best way to cook a fish?',
      'What is the best way to cook an egg?',
      'What is the best way to say "hello"?',
      'What is the best way to take notes: pen and paper, phone, or laptop?',
      'What is the best way to travel: car, train, or plane?',
      'What is the coolest brand of sneakers?',
      'What is the cutest baby animal?',
      'What is the first day of the work week?',
      'What is the first thing people notice when they walk into a home?',
      'What is the first thing you do when you wake up?',
      'What is the king of the biscuit/cookie world?',
      'What is the loudest animal?',
      'What is the main character zodiac sign?',
      'What is the most "main character" personality trait?',
      'What is the most annoying corporate buzzword?',
      'What is the most annoying thing about a smartphone?',
      'What is the most attractive musical instrument to play?',
      'What is the most basic clothing item?',
      'What is the most beautiful natural landmark in the world?',
      'What is the most boring job title?',
      'What is the most common fear?',
      'What is the most common first name?',
      'What is the most common lie people tell?',
      'What is the most common lucky number?',
      'What is the most common pet?',
      'What is the most controversial pizza topping (besides pineapple)?',
      'What is the most dangerous animal in the ocean?',
      'What is the most epic movie franchise?',
      'What is the most essential item in a winter wardrobe?',
      'What is the most essential item on a desk?',
      'What is the most famous city in the world?',
      'What is the most iconic Disney movie?',
      'What is the most important room in a house?',
      'What is the most popular soda brand?',
      'What is the most used app on your phone?',
      'What is the most useful website?',
      'What is the most versatile color for a t-shirt?',
      'What is the scariest insect?',
      'What is the scariest type of weather?',
      'What is the ultimate "movie night" candy or dessert?',
      'What is the worst day for a meeting?',
      'What time is too early to wake up?',
      'What was the coolest subject in school?',
      'What was the worst subject in school?',
      'Who is the best superhero?',
      'Who is the best villain?',
      "Name a bug that isn't scary.",
      "Name a city you'd visit for a romantic getaway.",
      "Name a common password people use (but shouldn't).",
      "Name a country you'd love to live in for a year.",
      "Name a fruit that doesn't belong in a fruit salad.",
      "Name a fruit that tastes better when it's cold.",
      "Name a genre of music you can't stand.",
      "Name a professional sport you'd never want to play.",
      "Name a reason to call in sick when you aren't.",
      "Name an animal that starts with the letter 'P'.",
      "Name an item you'd find in a hotel room.",
      "Name something you'd find on a teacher's desk.",
      "Name something you'd find under a sofa cushion.",
      "What is the best movie snack that isn't popcorn?",
      "What is the first thing you'd buy if you won the lottery?",
    ],
    Ito: [
      'Activities from least to most likely to make you viral on social media.',
      'Activities from least to most likely to result in a scar',
      'Animals and fantasy creatures from least to most cool to have as a pet',
      'Animals from least to most common',
      'Animals from least to most likely to be helpful as a personal chef',
      'Animals from least to most likely to secretly be plotting human extinction',
      'Animals which you least to most want to be',
      'Beverages from worst to best',
      'Cartoon characters from least to most likely to win a spelling bee',
      'Celebrities from least to most likeable',
      'Celebrities from least to most talented',
      'Celebrities from weakest to strongest in a fight',
      'Clothing items from least to most fashionable',
      'Crimes from least to most easy to get away with',
      'Dance moves from worst to best',
      'Desserts or sweets from worst to best',
      'Easiest to hardest things to give up for the rest of your life',
      'Easiest to hardest things to have to tell your parents',
      'Easiest to hardest things to steal',
      'Fast food menu items from worst to best',
      'Female celebrities from least to most attractive',
      'Fictional characters from least to most likely to be a nightmare to live with',
      'Fictional characters from weakest to strongest in a fight',
      'Fictional characters with the easiest to the hardest lives',
      'Fragrances and smells from worst to best',
      'Historical figures from least to most likely to survive a modern-day rave',
      'Hobbies from least to most interesting',
      'Horror movies you would least to most likely survive',
      'Household objects from least to most effective as a makeshift weapon',
      'Investments from least to most stable',
      'Items from least to most likely to be cursed by an ancient spirit',
      'Items from least to most useful in a fight',
      'Items or things people are least to most likely to own',
      'Jobs or professions from easiest to hardest',
      'Least to most intimidating villains from fiction',
      'Least to most likely thing for a cult to worship',
      'Magical curses you would inflict on your worst enemy from least to most cruel',
      'Male celebrities from least to most attractive',
      'Memes from least to most funny',
      'Movie/TV show endings from worst to best',
      'Movies and TV shows from least to most likely to make you laugh',
      'Movies or TV show moments from least to most likely to make you cry',
      'Musical artist or acts from worst to best',
      'Personality traits from least to most attractive',
      'Places to fart loudly from worst to best',
      'Places to hide a body from worst to best',
      'Problems that need to be solved by humanity from least to most important',
      'Professional athletes from weakest to strongest',
      'Scenarios from least to most annoying',
      'Scenarios from least to most cringe/awkward',
      'Scenarios from least to most likely to make you cry in public',
      'Scenarios from least to most likely to make you want to live in a cave for a year.',
      'Social issues from least to most important',
      'Songs from worst to best',
      'Sounds and noises from worst to best',
      'Superpowers from least to most powerful',
      'Things from least to most likely to make you quit your job on the spot',
      'Things or scenarios that cause the least to the most stress',
      'Things that are easiest to hardest to learn',
      'Things that are least to most cute',
      'Things that cause the least to the most pain',
      'Things that could happen in the afterlife from worst to best',
      'Things that happened in highschool from worst to best',
      'Things that least to most disgust you',
      'Things that least to most likely indicate someone is old',
      'Things that least to most likely indicate someone is young',
      'Things that would least to most improve your day',
      'Things that would least to most likely scare you',
      'Things to do as a group from least to most exciting',
      'Things to do just before you quit your job from worst to best',
      'Things to do on the internet from least to most entertaining',
      'Things to eat for breakfast from worst to best',
      'Things to pack for lunch from worst to best',
      'Things to put on your dating profile that would make you least to most successful',
      'Things to put on your resume from least to most impressive',
      'Things you are least to most likely to do in a bedroom',
      'Things you can cook at home from easiest to hardest',
      'Things you can find in a deep hole in the woods from least to most terrifying',
      'Things you can poke your finger in from worst to best',
      'Things you could purchase for $10,000 from least to most practical',
      'Things you least to most want to happen 10 years from now',
      'Things you least to most want to happen 300 years from now',
      'Things you least to most want to happen at your wedding',
      'Things you would do for $100 from easiest to hardest',
      'Things you would do for a million dollars from easiest to hardest',
      'Things you would do if you could turn invisible from worst to best',
      'Things you would do if you had a free day to yourself from least to most likely',
      'Things you would do if you had no money and were homeless from least to most likely',
      'Things you would do if you knew you would die tomorrow from worst to best',
      'Things you would do if you ruled the world from least to most cruel',
      'Things you would do if you saw a ghost from least to most likely',
      'Things you would do if you were a bird from least to most interesting',
      'Things you would do if you were the only person left on Earth from least to most likely',
      'Things you would put in a mansion you were building from least to most practical',
      'Ways to get high from worst to best',
      'Ways to make a child cry from least to most cruel',
      'Weekend activities from least to most fun',
      'World records from least to most impressive',
      'Worse to best things to do if you are a teacher',
      'Worst to best advice to give to a child',
      'Worst to best animals to have as a teammate in a game of hide and seek.',
      'Worst to best excuses for being late to work',
      'Worst to best flavours of ice cream',
      'Worst to best mottos to live by',
      'Worst to best nicknames to have',
      'Worst to best objects to use as a frisbee',
      'Worst to best objects to use as a makeshift hammer.',
      'Worst to best people from history to have dinner with',
      'Worst to best person to represent you in a criminal trial',
      'Worst to best places to find a piece of gum stuck',
      'Worst to best places to get food in your city',
      'Worst to best places to go swimming',
      'Worst to best places to hide a 2 meters tall giraffe statue',
      'Worst to best places to start dancing uncontrollably',
      'Worst to best places to take a piss',
      'Worst to best places to visit as a tourist',
      'Worst to best questions to ask on a first date',
      'Worst to best reasons for a riot to happen',
      'Worst to best reasons to become a supervillain',
      'Worst to best reasons to drop out of school',
      'Worst to best reasons to go on a quest',
      'Worst to best reasons to pursue a career in medicine',
      'Worst to best reasons to start a fight',
      'Worst to best reasons to write a strongly worded letter',
      'Worst to best snack foods',
      'Worst to best superhero names',
      'Worst to best thing to do if you found a dead body',
      'Worst to best thing to have the ability to conjure from thin air',
      'Worst to best things about being a vampire',
      'Worst to best things that would happen after winning a million dollars',
      'Worst to best things to be able to control with your mind',
      'Worst to best things to break',
      'Worst to best things to bring as your only item to a desert island',
      'Worst to best things to carry in your purse',
      'Worst to best things to catch while going fishing',
      'Worst to best things to challenge the grim reaper at to save your life',
      'Worst to best things to discover under your hotel bed',
      'Worst to best things to do at a restaurant',
      'Worst to best things to do everyday',
      'Worst to best things to do if you are stopped by the police',
      'Worst to best things to do if you are stranded on tropical island',
      'Worst to best things to do if you had an audience with the queen',
      'Worst to best things to do if you were suddenly transported back to the medieval ages',
      'Worst to best things to do in a crowded elevator',
      'Worst to best things to do in a zombie apocalypse',
      'Worst to best things to do on a first date',
      'Worst to best things to find out your house is haunted by.',
      'Worst to best things to find out your neighbor is "collecting"',
      'Worst to best things to get tattooed',
      'Worst to best things to give as a gift',
      'Worst to best things to have happen while you are giving a speech',
      'Worst to best things to have happen while you are on a balance beam',
      'Worst to best things to have to wear as your uniform at work',
      'Worst to best things to have written on your tombstone',
      'Worst to best things to hear a doctor say while you are going under anesthesia',
      'Worst to best things to hear a stranger whisper in your ear on a bus.',
      'Worst to best things to learn about your parents',
      'Worst to best things to lie about',
      'Worst to best things to make review videos of for a living',
      'Worst to best things to put in a smoothie',
      'Worst to best things to say to a pilot during a flight',
      'Worst to best things to say when you accidentally break a tall golden trophy',
      'Worst to best things to say when you accidentally walk into the wrong bathroom',
      'Worst to best things to search up on Google',
      'Worst to best things to see happen on a stage',
      'Worst to best things to see when you look out of an airplane window',
      'Worst to best things to serve at a 5 star restaurant',
      'Worst to best things to share on social media',
      'Worst to best things to use as a bookmark',
      'Worst to best things to write a song about',
      'Worst to best things you could do if you could freeze time',
      'Worst to best things you could say about someone',
      'Worst to best things you could use to blackmail someone with',
      'Worst to best things you would do if you could time travel',
      'Worst to best things your boss could tell you',
      'Worst to best things your parents did while you grew up',
      'Worst to best times in history you would travel to if you could time travel',
      'Worst to best ways for the world to end',
      'Worst to best ways to answer the question "Where do you see yourself in 5 years?"',
      'Worst to best ways to assert dominance',
      'Worst to best ways to break up with someone',
      'Worst to best ways to die',
      'Worst to best ways to get yourself to fall asleep',
      'Worst to best ways to make money',
      'Worst to best ways to propose marriage to someone',
      'Worst to best ways to spend your last $5',
      'Worst to best ways to travel 1000 kilometres',
      'Worst to best wish you would make if you could make any wish',
      "Animals you'd least to most likely beat in a fist fight",
      "Experiences from least to most impactful on someone's life",
      "Fictional characters you'd most want to be friends with",
      "Fictional worlds or settings you'd least to most like to live in",
      "Fights between any two fictional characters or creatures you'd least to most want to watch",
      "Items that are least to most likely to be found in a wizard's pocket",
      "People or things you'd least to most want on a deserted island with you",
      "People you'd least to most want to swap bodies with for a day",
      "Songs you'd hear at a karaoke night from least to most likely",
      "Things you've done in your life from least to most often",
      "Worst to best things to say when you forget the name of the person you're talking to.",
      "Worst to best ways to get everyone's attention",
    ],
    'Just One': [
      'Acorn',
      'Adidas',
      'Airplane',
      'Airport',
      'Alarm',
      'Amazon',
      'Anchor',
      'Apartment',
      'Apple',
      'Baby',
      'Backpack',
      'Bag',
      'Baker',
      'Ball',
      'Banana',
      'Bank',
      'Barbecue',
      'Barber',
      'Barbie',
      'Basket',
      'Bath',
      'Batman',
      'Battery',
      'Beach',
      'Bean',
      'Bear',
      'Beard',
      'Bed',
      'Bee',
      'Beef',
      'Beer',
      'Bell',
      'Belt',
      'Bench',
      'Berry',
      'Bicycle',
      'Billboard',
      'Bin',
      'Binoculars',
      'Bird',
      'Biscuit',
      'Blackboard',
      'Blanket',
      'Blender',
      'Blouse',
      'Boat',
      'Bone',
      'Bonfire',
      'Book',
      'Boot',
      'Bottle',
      'Bow',
      'Bowl',
      'Box',
      'Bracelet',
      'Brain',
      'Branch',
      'Bread',
      'Bridge',
      'Broom',
      'Brush',
      'Bubble',
      'Bucket',
      'Building',
      'Burger',
      'Burrito',
      'Bus',
      'Butter',
      'Butterfly',
      'Button',
      'Buzz Lightyear',
      'Cabin',
      'Cabinet',
      'Cactus',
      'Cafe',
      'Cafeteria',
      'Cage',
      'Cake',
      'Calendar',
      'Camel',
      'Camera',
      'Camp',
      'Canal',
      'Candle',
      'Candy',
      'Cannon',
      'Canoe',
      'Cap',
      'Car',
      'Caravan',
      'Card',
      'Cardboard',
      'Carnival',
      'Carpet',
      'Carrot',
      'Cart',
      'Carton',
      'Case',
      'Cash',
      'Casino',
      'Cassette',
      'Castle',
      'Cat',
      'Caterpillar',
      'Cave',
      'Ceiling',
      'Cellar',
      'Cemetery',
      'Cereal',
      'Chain',
      'Chair',
      'Chalk',
      'Check',
      'Cheese',
      'Chest',
      'Chewbacca',
      'Chicken',
      'Chime',
      'Chimney',
      'Chip',
      'Chocolate',
      'Church',
      'Cigarette',
      'Cinderella',
      'Cinema',
      'City',
      'Classroom',
      'Clinic',
      'Clock',
      'Cloud',
      'Clover',
      'Clown',
      'Coach',
      'Coal',
      'Coast',
      'Coat',
      'Coca-Cola',
      'Cockroach',
      'Cocktail',
      'Coconut',
      'Cocoon',
      'Coffee',
      'Coin',
      'Collar',
      'College',
      'Column',
      'Comb',
      'Compass',
      'Computer',
      'Concert',
      'Container',
      'Cooker',
      'Cookie',
      'Cork',
      'Corner',
      'Corridor',
      'Counter',
      'Court',
      'Cow',
      'Crab',
      'Crane',
      'Crayon',
      'Cream',
      'Crepe',
      'Crocodile',
      'Cross',
      'Crowd',
      'Crown',
      'Cucumber',
      'Cup',
      'Cupboard',
      'Cupid',
      'Curtain',
      'Cushion',
      'Cycle',
      'Dam',
      'Darth Vader',
      'Deck',
      'Deer',
      'Dentist',
      'Desert',
      'Desk',
      'Diamond',
      'Diary',
      'Dinner',
      'Dinosaur',
      'Dish',
      'Disney',
      'Doctor',
      'Dog',
      'Doll',
      'Dollar',
      'Dolphin',
      'Donkey',
      'Door',
      'Doorbell',
      'Doormat',
      'Dough',
      'Dracula',
      'Dragon',
      'Drawer',
      'Dress',
      'Drill',
      'Drum',
      'Duck',
      'Dune',
      'Dwarf',
      'Egg',
      'Elephant',
      'Elf',
      'Elsa',
      'Emperor',
      'Engine',
      'Envelope',
      'Facebook',
      'Fan',
      'Farm',
      'Feather',
      'Fence',
      'Ferrari',
      'Ferry',
      'Finger',
      'Fire',
      'Fireman',
      'Fish',
      'Flag',
      'Flame',
      'Flash',
      'Flower',
      'Foot',
      'Ford',
      'Forest',
      'Fork',
      'Fountain',
      'Fox',
      'Frankenstein',
      'Fridge',
      'Fries',
      'Fruit',
      'Galaxy',
      'Game',
      'Gandalf',
      'Garage',
      'Garden',
      'Garlic',
      'Gate',
      'Giant',
      'Gift',
      'Gladiator',
      'Glass',
      'Glasses',
      'Glove',
      'Glue',
      'Goat',
      'Godzilla',
      'Gold',
      'Golf',
      'Google',
      'Grape',
      'Gremlins',
      'Grenade',
      'Grotto',
      'Guillotine',
      'Guitar',
      'Gumbo',
      'Hammer',
      'Hand',
      'Handle',
      'Harry Potter',
      'Hat',
      'Heart',
      'Heel',
      'Helicopter',
      'Helmet',
      'Hercules',
      'Hockey',
      'Honey',
      'Hose',
      'Hospital',
      'Hotel',
      'House',
      'Hulk',
      'Ice',
      'IKEA',
      'Instagram',
      'iPhone',
      'Iron Man',
      'Island',
      'Jacket',
      'James Bond',
      'Jedi',
      'Jewelry',
      'Joker',
      'Juice',
      'Juliet',
      'Key',
      'KFC',
      'King Kong',
      'King',
      'Kitchen',
      'Knife',
      'Knight',
      'Ladder',
      'Ladybug',
      'Lake',
      'Lamp',
      'Laptop',
      'Lava',
      'Leaf',
      'Leg',
      'Lego',
      'Lemon',
      'Letter',
      'Library',
      'Lightbulb',
      'Lighthouse',
      'Lightning',
      'Lion',
      'Lock',
      'Luigi',
      'Machine',
      'Magician',
      'Magnet',
      'Map',
      'Mario',
      'Market',
      'Mars',
      'Mask',
      'Meat',
      'Medicine',
      'Melon',
      'Mickey',
      'Microsoft',
      'Milk',
      'Mirror',
      'Missile',
      'Money',
      'Monkey',
      'Monopoly',
      'Moon',
      'Mosquito',
      'Mountain',
      'Mouse',
      'Mouth',
      'Mower',
      'Mummy',
      'Museum',
      'Mushroom',
      'Mustard',
      'Nail',
      'Necklace',
      'Needle',
      'Nest',
      'Netflix',
      'Newspaper',
      'Nike',
      'Ninja',
      'Nintendo',
      'Noodle',
      'Nose',
      'Notebook',
      'Oasis',
      'Octopus',
      'Onion',
      'Opera',
      'Orange',
      'Oven',
      'Pac-Man',
      'Paint',
      'Painting',
      'Palace',
      'Pan',
      'Panda',
      'Paper',
      'Parachute',
      'Park',
      'Parrot',
      'Passport',
      'Peach',
      'Peanut',
      'Pear',
      'Pebble',
      'Pen',
      'Pencil',
      'Penguin',
      'Pepper',
      'Perfume',
      'Phone',
      'Piano',
      'Pie',
      'Pig',
      'Pigeon',
      'Pikachu',
      'Pillow',
      'Pipe',
      'Pirate',
      'Pizza',
      'Plane',
      'Plate',
      'PlayStation',
      'Poison',
      'Police',
      'Pony',
      'Pool',
      'Pope',
      'Popeye',
      'Postcard',
      'Pot',
      'Potato',
      'Powder',
      'Princess',
      'Printer',
      'Prison',
      'Puppet',
      'Purse',
      'Radio',
      'Rain',
      'Rake',
      'Ram',
      'Rambo',
      'Rat',
      'Restaurant',
      'Rice',
      'Ring',
      'River',
      'Road',
      'Robot',
      'Rock',
      'Rolex',
      'Romeo',
      'Roof',
      'Room',
      'Rooster',
      'Rope',
      'Rose',
      'Ruler',
      'Rum',
      'Safe',
      'Sail',
      'Salt',
      'Sand',
      'Sandwich',
      'Sausage',
      'Scale',
      'School',
      'Scissors',
      'Scrabble',
      'Screw',
      'Sea',
      'Seed',
      'Sewer',
      'Shack',
      'Shark',
      'Sheep',
      'Shelf',
      'Shell',
      'Sherlock',
      'Ship',
      'Shirt',
      'Shoe',
      'Shop',
      'Shovel',
      'Shower',
      'Shrek',
      'Shrimp',
      'Simba',
      'Simpson',
      'Sink',
      'Siren',
      'Ski',
      'Slipper',
      'Smoke',
      'Snake',
      'Snow',
      'Soap',
      'Sock',
      'Socket',
      'Sofa',
      'Sombrero',
      'Sonic',
      'Soup',
      'Spear',
      'Spice',
      'Spider-Man',
      'SpongeBob',
      'Spoon',
      'Spy',
      'Star',
      'Starbucks',
      'Station',
      'Stew',
      'Stone',
      'Strawberry',
      'Street',
      'String',
      'Subway',
      'Sugar',
      'Sun',
      'Superman',
      'Sword',
      'Syrup',
      'Table',
      'Tarzan',
      'Tattoo',
      'Taxi',
      'Tea',
      'Teacher',
      'Teapot',
      'Telephone',
      'Television',
      'Temple',
      'Tennis',
      'Terminator',
      'Tetris',
      'Thunder',
      'Ticket',
      'Tie',
      'Tiger',
      'Titanic',
      'Tobacco',
      'Tomato',
      'Tool',
      'Toothbrush',
      'Towel',
      'Tower',
      'Train',
      'Treasure',
      'Tree',
      'Triangle',
      'Truck',
      'Tuna',
      'Tunnel',
      'Umbrella',
      'Unicorn',
      'Uniform',
      'Vampire',
      'Vase',
      'Vegetable',
      'Venus',
      'Viking',
      'Violin',
      'Volcano',
      'Voldemort',
      'Wallet',
      'Watch',
      'Water',
      'Wave',
      'Whale',
      'Wheat',
      'Wheel',
      'Wind',
      'Window',
      'Wine',
      'Wolf',
      'Yoda',
      'YouTube',
      'Zebra',
      'Zombie',
      'Zoo',
      "McDonald's",
    ],
  };

  function shuffle(array) {
    const r = [...array];
    for (let i = r.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [r[i], r[j]] = [r[j], r[i]];
    }
    return r;
  }

  function init() {
    const state = {};
    for (const [name, items] of Object.entries(CATEGORIES)) {
      state[name] = {
        deck: shuffle(items),
        index: 0,
      };
    }

    function getNextPrompt(categoryName) {
      const cat = state[categoryName];
      const item = cat.deck[cat.index];
      cat.index += 1;
      if (cat.index >= cat.deck.length) {
        cat.index = 0;
      }
      return item;
    }

    const container = document.getElementById('categoryBtns');
    const modal = new bootstrap.Modal(document.getElementById('promptModal'));
    const promptText = document.getElementById('promptText');
    const promptNextBtn = document.getElementById('promptNextBtn');
    let currentCategory = null;

    for (const name of Object.keys(CATEGORIES)) {
      const btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'btn btn-primary btn-lg p-3 fs-4';
      btn.textContent = name;
      btn.addEventListener('click', () => {
        currentCategory = name;
        promptText.textContent = getNextPrompt(name);
        modal.show();
      });
      container.appendChild(btn);
    }

    promptNextBtn.addEventListener('click', () => {
      if (currentCategory) {
        promptText.textContent = getNextPrompt(currentCategory);
      }
    });
  }

  document.addEventListener('DOMContentLoaded', init);
})();
